# =============================================================================
# 03_dna_model_inference.py
# Airflow DAG: dna_model_inference_pipeline
#
# Orchestrates:
#   1. Verify variants table is populated
#   2. Download DNABERT-2 weights from HuggingFace
#   3. Download HyenaDNA weights from HuggingFace
#   4. DNABERT-2 inference: embed 512 bp windows → dna_model_predictions
#   5. HyenaDNA inference: embed 4096 bp windows → dna_model_predictions
#   6. LLM ensemble narrative generation (BioMistral-7B, Llama-3.1-8B, Qwen3-8B)
#   7. Refresh Apache Superset dashboards
#   8. Mark pipeline run complete
#
# Pre-requisites (in airflow worker image):
#   torch, transformers, huggingface_hub, requests, psycopg2
# =============================================================================

from __future__ import annotations

import json
import logging
import os
import re
import time
import uuid
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from airflow import DAG
from airflow.operators.python import PythonOperator

import dag_utils

log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
DAG_ID = "dna_model_inference_pipeline"
DAG_OWNER = "biointel"

MODELS_DIR = Path("/opt/biointel/models")
DATA_DIR = Path("/opt/biointel/data")

DNABERT2_REPO = "zhihan1996/DNABERT-2-117M"
HYENADNA_REPO = "LongSafari/hyenadna-small-32k-seqlen-hf"

DNABERT2_WINDOW = 512    # base pairs around each variant
HYENADNA_WINDOW = 4096   # base pairs around each variant
TOP_VARIANTS = 1000       # number of variants to embed per run

ETHICAL_DISCLAIMER = (
    "RESEARCH USE ONLY. This narrative was generated by an AI ensemble for "
    "exploratory research purposes. It does NOT constitute a clinical diagnosis, "
    "medical advice, or genetic counselling. Genetic ancestry principal "
    "components are mathematical coordinates, not racial classifications. "
    "Any interpretations must be validated by qualified experts before any "
    "research or clinical use."
)

LLM_ENSEMBLE_MODELS = [
    {
        "repo_id": "BioMistral/BioMistral-7B",
        "short_name": "BioMistral-7B",
        "local_dir": str(MODELS_DIR / "BioMistral-7B"),
    },
    {
        "repo_id": "meta-llama/Meta-Llama-3.1-8B-Instruct",
        "short_name": "Llama-3.1-8B",
        "local_dir": str(MODELS_DIR / "Llama-3.1-8B"),
    },
    {
        "repo_id": "Qwen/Qwen3-8B",
        "short_name": "Qwen3-8B",
        "local_dir": str(MODELS_DIR / "Qwen3-8B"),
    },
]

SUPERSET_URL = os.getenv("SUPERSET_URL", "http://superset:8088")
SUPERSET_USERNAME = os.getenv("SUPERSET_USERNAME", "admin")
SUPERSET_PASSWORD = os.getenv("SUPERSET_PASSWORD", "admin")
# IDs of the 5 BioIntelligence dashboards in Superset
SUPERSET_DASHBOARD_IDS = [1, 2, 3, 4, 5]

default_args: Dict[str, Any] = {
    "owner": DAG_OWNER,
    "depends_on_past": False,
    "email_on_failure": False,
    "email_on_retry": False,
    "retries": 1,
    "retry_delay": timedelta(minutes=10),
}

# ---------------------------------------------------------------------------
# Task functions
# ---------------------------------------------------------------------------


def _check_variants_available(**context: Any) -> None:
    """Verify that the variants table has rows before running inference."""
    conn = dag_utils.get_pg_conn()
    try:
        result = dag_utils.fetch_one(conn, "SELECT COUNT(*) AS n FROM variants")
        n = result["n"] if result else 0
        log.info("Variants in DB: %d", n)
        if n == 0:
            raise ValueError(
                "variants table is empty — run genetics_qc_pca_pipeline first."
            )
    finally:
        conn.close()

    run_id = dag_utils.log_pipeline_start(DAG_ID, config={"step": "dna_model_inference"})
    dag_utils.push_run_id(context, run_id)
    log.info("Started pipeline run_id=%s", run_id)


def _download_dnabert2_weights(**context: Any) -> None:
    """
    Download DNABERT-2 weights from HuggingFace Hub into the models cache.
    Idempotent: snapshot_download skips files already present.
    """
    from huggingface_hub import snapshot_download  # type: ignore

    log.info("Downloading DNABERT-2 (%s) to %s …", DNABERT2_REPO, MODELS_DIR)
    local_dir = snapshot_download(
        repo_id=DNABERT2_REPO,
        cache_dir=str(MODELS_DIR),
        local_files_only=False,
        ignore_patterns=["*.msgpack", "flax*", "tf_*"],
    )
    log.info("DNABERT-2 weights available at: %s", local_dir)
    context["ti"].xcom_push(key="dnabert2_local_dir", value=local_dir)


def _download_hyenadna_weights(**context: Any) -> None:
    """
    Download HyenaDNA weights from HuggingFace Hub.
    Idempotent.
    """
    from huggingface_hub import snapshot_download  # type: ignore

    log.info("Downloading HyenaDNA (%s) to %s …", HYENADNA_REPO, MODELS_DIR)
    local_dir = snapshot_download(
        repo_id=HYENADNA_REPO,
        cache_dir=str(MODELS_DIR),
        local_files_only=False,
        ignore_patterns=["*.msgpack", "flax*", "tf_*"],
    )
    log.info("HyenaDNA weights available at: %s", local_dir)
    context["ti"].xcom_push(key="hyenadna_local_dir", value=local_dir)


def _fetch_reference_sequence(chrom: str, pos: int, window: int) -> Optional[str]:
    """
    Attempt to fetch a DNA sequence window from Ensembl REST API.
    Falls back to a synthetic poly-N string on failure (for pipeline
    robustness — embeddings on poly-N are flagged/discarded downstream).

    Parameters
    ----------
    chrom : str
        Chromosome (without 'chr' prefix expected by Ensembl).
    pos : int
        1-based position of the variant (GRCh37/38 coords).
    window : int
        Total window size in base pairs (variant centered).

    Returns
    -------
    str | None
        DNA sequence string, uppercased, or None on failure.
    """
    import urllib.request

    half = window // 2
    start = max(1, pos - half)
    end = pos + half

    # Strip 'chr' prefix for Ensembl
    chrom_clean = chrom.lstrip("chr")

    url = (
        f"https://rest.ensembl.org/sequence/region/human/"
        f"{chrom_clean}:{start}..{end}?content-type=text/plain"
    )
    try:
        with urllib.request.urlopen(url, timeout=10) as resp:
            seq = resp.read().decode("utf-8").strip().upper()
            return seq
    except Exception as exc:
        log.debug("Ensembl sequence fetch failed for %s:%d: %s", chrom, pos, exc)
        return "N" * window  # synthetic fallback


def _run_dnabert2_inference(**context: Any) -> None:
    """
    Load DNABERT-2, fetch top-N variants from the DB, embed 512 bp windows,
    and store results in dna_model_predictions.
    """
    import torch  # type: ignore
    from transformers import AutoTokenizer, AutoModel  # type: ignore

    local_dir = context["ti"].xcom_pull(key="dnabert2_local_dir")
    if not local_dir:
        # Fallback: look in cache using repo id conventions
        local_dir = str(MODELS_DIR)

    log.info("Loading DNABERT-2 from %s …", local_dir)
    device = "cuda" if torch.cuda.is_available() else "cpu"
    log.info("Inference device: %s", device)

    try:
        tokenizer = AutoTokenizer.from_pretrained(
            local_dir, trust_remote_code=True
        )
        model = AutoModel.from_pretrained(
            local_dir, trust_remote_code=True
        ).to(device).eval()
    except Exception as exc:
        raise RuntimeError(f"Failed to load DNABERT-2 from {local_dir}: {exc}") from exc

    # Fetch top variants from DB (order by gnomad_af DESC as proxy for interest)
    conn = dag_utils.get_pg_conn()
    try:
        variants = dag_utils.fetch_all(
            conn,
            """
            SELECT v.variant_id, v.chrom, v.pos, v.ref, v.alt,
                   sv.subject_id
            FROM   variants v
            JOIN   subject_variants sv ON v.variant_id = sv.variant_id
            WHERE  v.gnomad_af IS NOT NULL
            ORDER  BY v.gnomad_af DESC
            LIMIT  %s
            """,
            (TOP_VARIANTS,),
        )
        log.info("Fetched %d variant-subject pairs for DNABERT-2", len(variants))
    finally:
        conn.close()

    if not variants:
        log.warning("No variants found — DNABERT-2 inference skipped.")
        return

    model_name = "DNABERT-2"
    model_version = DNABERT2_REPO

    rows: List[tuple] = []
    for rec in variants:
        chrom = rec["chrom"]
        pos = rec["pos"]
        subject_id = rec["subject_id"]
        variant_id = rec["variant_id"]

        seq = _fetch_reference_sequence(chrom, pos, DNABERT2_WINDOW)
        if seq is None:
            continue

        try:
            inputs = tokenizer(
                seq,
                return_tensors="pt",
                truncation=True,
                max_length=512,
                padding="max_length",
            ).to(device)

            with torch.no_grad():
                outputs = model(**inputs)
                # CLS token embedding: shape (1, hidden_dim)
                cls_embedding = outputs.last_hidden_state[:, 0, :].squeeze(0)
                embedding_list = cls_embedding.cpu().float().tolist()

            pred_score = float(cls_embedding.norm().item())  # L2 norm as proxy score

            rows.append((
                subject_id,
                model_name,
                model_version,
                seq[:200],            # store first 200bp for reference
                embedding_list,
                None,                 # pred_label — downstream classification task
                pred_score,
                variant_id,
            ))
        except Exception as exc:
            log.warning("DNABERT-2 inference failed for variant %s: %s", variant_id, exc)
            continue

        # Flush every 100 rows
        if len(rows) >= 100:
            _flush_dna_predictions(rows)
            rows.clear()

    if rows:
        _flush_dna_predictions(rows)

    log.info("DNABERT-2 inference complete: %d embeddings stored", len(variants))
    context["ti"].xcom_push(key="dnabert2_n_embedded", value=len(variants))


def _flush_dna_predictions(rows: List[tuple]) -> None:
    """Insert a batch of dna_model_predictions rows."""
    conn = dag_utils.get_pg_conn()
    try:
        dag_utils.bulk_insert(
            conn,
            "dna_model_predictions",
            ["subject_id", "model_name", "model_version", "sequence_context",
             "embedding", "pred_label", "pred_score", "variant_id"],
            rows,
            on_conflict="DO NOTHING",
        )
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def _run_hyenadna_inference(**context: Any) -> None:
    """
    Load HyenaDNA, fetch top-N variants, embed 4096 bp windows,
    store results in dna_model_predictions.
    """
    import torch  # type: ignore
    from transformers import AutoTokenizer, AutoModelForCausalLM  # type: ignore

    local_dir = context["ti"].xcom_pull(key="hyenadna_local_dir")
    if not local_dir:
        local_dir = str(MODELS_DIR)

    log.info("Loading HyenaDNA from %s …", local_dir)
    device = "cuda" if torch.cuda.is_available() else "cpu"
    log.info("Inference device: %s", device)

    try:
        tokenizer = AutoTokenizer.from_pretrained(
            local_dir, trust_remote_code=True
        )
        # HyenaDNA uses a causal LM architecture; we extract hidden states
        model = AutoModelForCausalLM.from_pretrained(
            local_dir,
            trust_remote_code=True,
            output_hidden_states=True,
        ).to(device).eval()
    except Exception as exc:
        raise RuntimeError(f"Failed to load HyenaDNA from {local_dir}: {exc}") from exc

    # Fetch variants — same top-N as DNABERT-2 for comparability
    conn = dag_utils.get_pg_conn()
    try:
        variants = dag_utils.fetch_all(
            conn,
            """
            SELECT v.variant_id, v.chrom, v.pos, v.ref, v.alt,
                   sv.subject_id
            FROM   variants v
            JOIN   subject_variants sv ON v.variant_id = sv.variant_id
            WHERE  v.gnomad_af IS NOT NULL
            ORDER  BY v.gnomad_af DESC
            LIMIT  %s
            """,
            (TOP_VARIANTS,),
        )
        log.info("Fetched %d variant-subject pairs for HyenaDNA", len(variants))
    finally:
        conn.close()

    if not variants:
        log.warning("No variants found — HyenaDNA inference skipped.")
        return

    model_name = "HyenaDNA"
    model_version = HYENADNA_REPO

    rows: List[tuple] = []
    for rec in variants:
        chrom = rec["chrom"]
        pos = rec["pos"]
        subject_id = rec["subject_id"]
        variant_id = rec["variant_id"]

        seq = _fetch_reference_sequence(chrom, pos, HYENADNA_WINDOW)
        if seq is None:
            continue

        try:
            inputs = tokenizer(
                seq,
                return_tensors="pt",
                truncation=True,
                max_length=HYENADNA_WINDOW,
                padding="max_length",
            ).to(device)

            with torch.no_grad():
                outputs = model(**inputs)
                # Use last hidden state mean-pooled as the embedding
                # outputs.hidden_states[-1]: (1, seq_len, hidden_dim)
                hidden = outputs.hidden_states[-1].squeeze(0)   # (seq_len, hidden_dim)
                embedding_vec = hidden.mean(dim=0)              # (hidden_dim,)
                embedding_list = embedding_vec.cpu().float().tolist()

            pred_score = float(embedding_vec.norm().item())

            rows.append((
                subject_id,
                model_name,
                model_version,
                seq[:200],
                embedding_list,
                None,
                pred_score,
                variant_id,
            ))
        except Exception as exc:
            log.warning("HyenaDNA inference failed for variant %s: %s", variant_id, exc)
            continue

        if len(rows) >= 100:
            _flush_dna_predictions(rows)
            rows.clear()

    if rows:
        _flush_dna_predictions(rows)

    log.info("HyenaDNA inference complete: %d embeddings stored", len(variants))
    context["ti"].xcom_push(key="hyenadna_n_embedded", value=len(variants))


def _run_llm_ensemble_narrative(**context: Any) -> None:
    """
    For each subject that has both genetics (PCA) and MRI data:
      1. Gather summary statistics from the DB
      2. Build a structured research prompt
      3. Query each of the 3 LLMs in the ensemble
      4. Combine outputs (majority-vote / concatenation)
      5. Insert into llm_narratives with mandatory ethical_disclaimer

    Uses transformers pipeline for local inference to avoid external API calls.
    """
    import torch  # type: ignore
    from transformers import pipeline as hf_pipeline  # type: ignore
    from huggingface_hub import snapshot_download  # type: ignore

    device = 0 if torch.cuda.is_available() else -1  # transformers pipeline device id
    log.info("LLM inference device: %s", "cuda:0" if device == 0 else "cpu")

    # Fetch subjects with both modalities
    conn = dag_utils.get_pg_conn()
    try:
        subjects = dag_utils.fetch_all(
            conn,
            """
            SELECT s.subject_id, s.sex, s.age_at_scan, s.dataset_source,
                   ap.pc1, ap.pc2, ap.pc3,
                   COUNT(DISTINCT bm.region) AS n_brain_regions,
                   COUNT(DISTINCT sv.variant_id) AS n_variants
            FROM   subjects s
            JOIN   ancestry_pca     ap ON s.subject_id = ap.subject_id
            JOIN   brain_morphometry bm ON s.subject_id = bm.subject_id
            LEFT JOIN subject_variants sv ON s.subject_id = sv.subject_id
            WHERE  s.has_genetics = TRUE AND s.has_mri = TRUE
            GROUP  BY s.subject_id, s.sex, s.age_at_scan, s.dataset_source,
                      ap.pc1, ap.pc2, ap.pc3
            LIMIT  50
            """,
        )
        log.info("Subjects eligible for narrative generation: %d", len(subjects))
    finally:
        conn.close()

    if not subjects:
        log.warning("No subjects with both genetics and MRI — skipping narrative generation.")
        return

    # Download and load each LLM (download is idempotent)
    loaded_models: List[Dict[str, Any]] = []
    for model_spec in LLM_ENSEMBLE_MODELS:
        try:
            log.info("Downloading/loading LLM: %s", model_spec["short_name"])
            local_dir = snapshot_download(
                repo_id=model_spec["repo_id"],
                cache_dir=str(MODELS_DIR),
                local_files_only=False,
                ignore_patterns=["*.msgpack", "flax*", "tf_*", "*.ot"],
            )
            pipe = hf_pipeline(
                "text-generation",
                model=local_dir,
                tokenizer=local_dir,
                device=device,
                torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
                max_new_tokens=512,
                do_sample=False,
                temperature=1.0,
                trust_remote_code=True,
            )
            loaded_models.append({
                "short_name": model_spec["short_name"],
                "pipe": pipe,
                "local_dir": local_dir,
            })
            log.info("  ✓ Loaded %s", model_spec["short_name"])
        except Exception as exc:
            log.warning("Failed to load %s: %s — skipping this model.", model_spec["short_name"], exc)

    if not loaded_models:
        raise RuntimeError("No LLMs could be loaded for narrative generation.")

    # Generate narratives per subject
    narrative_rows: List[tuple] = []

    PROMPT_TEMPLATE = (
        "You are a research AI assistant helping neuroscientists summarize "
        "multi-modal biomedical data. Generate a concise, factual research "
        "narrative for the following subject. Do NOT make clinical diagnoses.\n\n"
        "Subject ID: {subject_id}\n"
        "Dataset: {dataset_source}\n"
        "Sex: {sex}\n"
        "Age at scan: {age_at_scan}\n"
        "Ancestry PC1: {pc1:.4f}, PC2: {pc2:.4f}, PC3: {pc3:.4f} "
        "(continuous genotype-space coordinates; not racial categories)\n"
        "Number of variants analysed: {n_variants}\n"
        "Brain regions segmented: {n_brain_regions}\n\n"
        "Provide a 3-4 sentence summary suitable for a research methods section."
    )

    for subj in subjects:
        prompt = PROMPT_TEMPLATE.format(
            subject_id=subj["subject_id"],
            dataset_source=subj.get("dataset_source", "unknown"),
            sex=subj.get("sex") or "U",
            age_at_scan=subj.get("age_at_scan") or 0.0,
            pc1=subj.get("pc1") or 0.0,
            pc2=subj.get("pc2") or 0.0,
            pc3=subj.get("pc3") or 0.0,
            n_variants=subj.get("n_variants") or 0,
            n_brain_regions=subj.get("n_brain_regions") or 0,
        )

        model_outputs: Dict[str, str] = {}
        for m in loaded_models:
            try:
                result = m["pipe"](prompt, pad_token_id=m["pipe"].tokenizer.eos_token_id)
                generated = result[0]["generated_text"]
                # Strip the prompt from the output if echoed
                if generated.startswith(prompt):
                    generated = generated[len(prompt):].strip()
                model_outputs[m["short_name"]] = generated
            except Exception as exc:
                log.warning(
                    "Narrative generation failed for subject %s with %s: %s",
                    subj["subject_id"], m["short_name"], exc,
                )
                model_outputs[m["short_name"]] = f"[Generation failed: {exc}]"

        # Primary narrative: first successful model; ensemble detail in JSONB
        primary_narrative = next(
            (v for v in model_outputs.values() if not v.startswith("[Generation failed")),
            "[All LLMs failed to generate narrative]",
        )
        primary_model = next(
            (k for k, v in model_outputs.items() if v == primary_narrative),
            loaded_models[0]["short_name"],
        )

        ensemble_json = json.dumps({
            "models": {k: v[:500] for k, v in model_outputs.items()},
            "strategy": "first_success",
        })
        generation_params = json.dumps({
            "max_new_tokens": 512,
            "do_sample": False,
            "ensemble_size": len(loaded_models),
        })

        narrative_rows.append((
            subj["subject_id"],
            "combined",                # analysis_type
            primary_narrative,
            primary_model,
            ensemble_json,
            "research_combined_v1",    # prompt_template
            generation_params,
            ETHICAL_DISCLAIMER,
        ))

    # Bulk insert narratives
    if narrative_rows:
        conn = dag_utils.get_pg_conn()
        try:
            dag_utils.bulk_insert(
                conn,
                "llm_narratives",
                ["subject_id", "analysis_type", "narrative_text", "model_name",
                 "model_ensemble", "prompt_template", "generation_params",
                 "ethical_disclaimer"],
                narrative_rows,
                on_conflict="DO NOTHING",
            )
            conn.commit()
            log.info("Inserted %d LLM narratives", len(narrative_rows))
        except Exception:
            conn.rollback()
            raise
        finally:
            conn.close()

    context["ti"].xcom_push(key="n_narratives", value=len(narrative_rows))


def _update_superset_dashboards(**context: Any) -> None:
    """
    Authenticate with Apache Superset and trigger a cache refresh
    on all 5 BioIntelligence dashboards.

    API flow:
      POST /api/v1/security/login → access_token
      PUT  /api/v1/dashboard/{id}/cache → trigger refresh per dashboard
    """
    import urllib.request

    def _api_request(
        url: str,
        method: str = "GET",
        data: Optional[bytes] = None,
        headers: Optional[Dict[str, str]] = None,
    ) -> Dict[str, Any]:
        req = urllib.request.Request(url, data=data, method=method)
        if headers:
            for k, v in headers.items():
                req.add_header(k, v)
        try:
            with urllib.request.urlopen(req, timeout=30) as resp:
                body = resp.read().decode("utf-8")
                return json.loads(body) if body else {}
        except urllib.error.HTTPError as exc:
            body = exc.read().decode("utf-8") if exc.fp else ""
            log.warning("Superset API error %d: %s", exc.code, body[:200])
            return {"error": str(exc), "body": body[:500]}
        except Exception as exc:
            log.warning("Superset request failed: %s", exc)
            return {"error": str(exc)}

    log.info("Authenticating with Superset at %s …", SUPERSET_URL)
    login_payload = json.dumps({
        "username": SUPERSET_USERNAME,
        "password": SUPERSET_PASSWORD,
        "provider": "db",
        "refresh": True,
    }).encode("utf-8")

    login_resp = _api_request(
        f"{SUPERSET_URL}/api/v1/security/login",
        method="POST",
        data=login_payload,
        headers={"Content-Type": "application/json"},
    )
    access_token = login_resp.get("access_token")
    if not access_token:
        log.warning(
            "Failed to obtain Superset access token: %s — skipping dashboard refresh.",
            login_resp,
        )
        return

    auth_headers = {
        "Authorization": f"Bearer {access_token}",
        "Content-Type": "application/json",
    }

    refresh_results: Dict[int, bool] = {}
    for dashboard_id in SUPERSET_DASHBOARD_IDS:
        # Invalidate cache and trigger refresh
        put_url = f"{SUPERSET_URL}/api/v1/dashboard/{dashboard_id}/cache"
        resp = _api_request(put_url, method="PUT", headers=auth_headers)
        success = "error" not in resp
        refresh_results[dashboard_id] = success
        log.info(
            "Dashboard %d refresh: %s",
            dashboard_id, "OK" if success else f"FAILED — {resp.get('error', '')}"
        )
        time.sleep(0.5)  # be polite to Superset

    n_ok = sum(1 for v in refresh_results.values() if v)
    log.info(
        "Superset refresh complete: %d/%d dashboards refreshed successfully",
        n_ok, len(SUPERSET_DASHBOARD_IDS),
    )
    context["ti"].xcom_push(key="superset_refresh_results", value=refresh_results)


def _update_pipeline_run(**context: Any) -> None:
    """Mark the pipeline run complete."""
    run_id = dag_utils.pull_run_id(context)
    if not run_id:
        log.warning("No run_id in XCom — skipping pipeline_runs update")
        return
    n_embedded = (
        (context["ti"].xcom_pull(key="dnabert2_n_embedded") or 0)
        + (context["ti"].xcom_pull(key="hyenadna_n_embedded") or 0)
    )
    dag_utils.log_pipeline_complete(run_id, n_subjects=n_embedded)
    log.info("Pipeline run_id=%s marked complete (n_embeddings=%d)", run_id, n_embedded)


# ---------------------------------------------------------------------------
# DAG definition
# ---------------------------------------------------------------------------

with DAG(
    dag_id=DAG_ID,
    description="DNABERT-2 + HyenaDNA inference, LLM narrative ensemble, Superset refresh",
    default_args=default_args,
    schedule=None,
    start_date=datetime(2024, 1, 1),
    catchup=False,
    max_active_runs=1,
    tags=["biointel", "dna-models", "llm", "inference", "superset"],
) as dag:

    # ------------------------------------------------------------------
    # Task 1: Check variants available
    # ------------------------------------------------------------------
    check_variants_available = PythonOperator(
        task_id="check_variants_available",
        python_callable=_check_variants_available,
    )

    # ------------------------------------------------------------------
    # Task 2: Download DNABERT-2 weights
    # ------------------------------------------------------------------
    download_dnabert2_weights = PythonOperator(
        task_id="download_dnabert2_weights",
        python_callable=_download_dnabert2_weights,
        execution_timeout=timedelta(hours=4),
    )

    # ------------------------------------------------------------------
    # Task 3: Download HyenaDNA weights
    # ------------------------------------------------------------------
    download_hyenadna_weights = PythonOperator(
        task_id="download_hyenadna_weights",
        python_callable=_download_hyenadna_weights,
        execution_timeout=timedelta(hours=4),
    )

    # ------------------------------------------------------------------
    # Task 4: DNABERT-2 inference
    # ------------------------------------------------------------------
    run_dnabert2_inference = PythonOperator(
        task_id="run_dnabert2_inference",
        python_callable=_run_dnabert2_inference,
        execution_timeout=timedelta(hours=6),
    )

    # ------------------------------------------------------------------
    # Task 5: HyenaDNA inference
    # ------------------------------------------------------------------
    run_hyenadna_inference = PythonOperator(
        task_id="run_hyenadna_inference",
        python_callable=_run_hyenadna_inference,
        execution_timeout=timedelta(hours=6),
    )

    # ------------------------------------------------------------------
    # Task 6: LLM ensemble narrative generation
    # ------------------------------------------------------------------
    run_llm_ensemble_narrative = PythonOperator(
        task_id="run_llm_ensemble_narrative",
        python_callable=_run_llm_ensemble_narrative,
        execution_timeout=timedelta(hours=8),
    )

    # ------------------------------------------------------------------
    # Task 7: Refresh Superset dashboards
    # ------------------------------------------------------------------
    update_superset_dashboards = PythonOperator(
        task_id="update_superset_dashboards",
        python_callable=_update_superset_dashboards,
        execution_timeout=timedelta(minutes=15),
    )

    # ------------------------------------------------------------------
    # Task 8: Mark pipeline run complete
    # ------------------------------------------------------------------
    update_pipeline_run = PythonOperator(
        task_id="update_pipeline_run",
        python_callable=_update_pipeline_run,
        trigger_rule="all_done",
    )

    # ------------------------------------------------------------------
    # Task dependencies
    #
    #   check_variants_available
    #       ├── download_dnabert2_weights ──► run_dnabert2_inference ──►┐
    #       └── download_hyenadna_weights ──► run_hyenadna_inference ──►┤
    #                                                                    ▼
    #                                              run_llm_ensemble_narrative
    #                                                         │
    #                                              update_superset_dashboards
    #                                                         │
    #                                               update_pipeline_run
    # ------------------------------------------------------------------
    check_variants_available >> [download_dnabert2_weights, download_hyenadna_weights]
    download_dnabert2_weights >> run_dnabert2_inference
    download_hyenadna_weights >> run_hyenadna_inference
    [run_dnabert2_inference, run_hyenadna_inference] >> run_llm_ensemble_narrative
    run_llm_ensemble_narrative >> update_superset_dashboards
    update_superset_dashboards >> update_pipeline_run
