#!/usr/bin/env python3
"""
auth_utils.py — Secure User Authentication Utilities for BioIntelligence Platform.
Provides PBKDF2 password hashing, registration verification, forgot password recovery
via security questions, invite/referral codes tracking, and Streamlit session gatekeeping.
"""

import os
import sys
import hashlib
import secrets
import sqlite3
import pandas as pd
import streamlit as st

project_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(project_dir, "scripts"))
import crypto_utils
DB_FILE = os.path.join(project_dir, "biointel.db")

# Standard list of security questions
SECURITY_QUESTIONS = [
    "What was the name of your first pet?",
    "What is your mother's maiden name?",
    "What was the name of your elementary school?",
    "In what city were you born?",
    "What is the name of your favorite book?"
]

# =========================================================================
# 1. Hashing & Verification
# =========================================================================

def hash_password(password: str, salt: str = None) -> tuple[str, str]:
    """Hash password securely using PBKDF2 algorithm with a salt."""
    if salt is None:
        salt = secrets.token_hex(16)
    
    pwd_hash = hashlib.pbkdf2_hmac(
        'sha256',
        password.encode('utf-8'),
        salt.encode('utf-8'),
        100000
    ).hex()
    
    return pwd_hash, salt

def verify_password(password: str, pwd_hash: str, salt: str) -> bool:
    """Verify password by comparing hashes."""
    check_hash, _ = hash_password(password, salt)
    return secrets.compare_digest(pwd_hash, check_hash)

# =========================================================================
# 2. Registration & Referral/Invite Codes
# =========================================================================

def verify_invite_code(code: str) -> bool:
    """Verify if invite code is active, matches DB records, and has available uses."""
    code = code.strip()
    if not code:
        return False
        
    conn = sqlite3.connect(DB_FILE)
    cur = conn.cursor()
    cur.execute("SELECT max_uses, used_count, status FROM invite_codes WHERE code = ?", (code,))
    row = cur.fetchone()
    conn.close()
    
    if row:
        max_uses, used_count, status = row[0], row[1], row[2]
        return status == "active" and used_count < max_uses
    return False

def generate_referral_code(username: str, max_uses: int = 1, allotted_credits: int = None) -> str:
    """Generate a unique referral invite code for a user."""
    username_clean = username.strip().upper()
    random_suffix = secrets.token_hex(3).upper()
    code = f"REF_{username_clean}_{random_suffix}"
    
    conn = sqlite3.connect(DB_FILE)
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO invite_codes (code, created_by, max_uses, used_count, allotted_credits) VALUES (?, ?, ?, 0, ?)",
        (code, username, max_uses, allotted_credits)
    )
    conn.commit()
    conn.close()
    return code

def get_user_referral_codes(username: str) -> pd.DataFrame:
    """Retrieve all codes generated by a user."""
    conn = sqlite3.connect(DB_FILE)
    df = pd.read_sql_query(
        "SELECT code, max_uses, used_count, status, allotted_credits, created_at FROM invite_codes WHERE created_by = ? ORDER BY created_at DESC",
        conn,
        params=(username,)
    )
    conn.close()
    return df

def get_referral_audit_log() -> pd.DataFrame:
    """Retrieve audit log mapping registered users to their referrers and codes."""
    conn = sqlite3.connect(DB_FILE)
    df = pd.read_sql_query(
        """
        SELECT 
            u.username AS registered_user,
            u.created_at AS registered_at,
            u.referred_by_code AS referral_code,
            ic.created_by AS referred_by_employee,
            ic.allotted_credits AS initial_credits,
            u.credits_remaining AS remaining_credits
        FROM users u
        LEFT JOIN invite_codes ic ON u.referred_by_code = ic.code
        ORDER BY u.created_at DESC
        """,
        conn
    )
    conn.close()
    return df

def register_user(username: str, password: str, email: str = None, 
                  sq1: str = None, sa1: str = None,
                  sq2: str = None, sa2: str = None,
                  referred_by_code: str = None) -> bool:
    """Insert a new user record and link them to their referrer invite code."""
    username = username.strip()
    if not username:
        raise ValueError("Username cannot be empty.")
    if len(password) < 4:
        raise ValueError("Password must be at least 4 characters long.")
    if not sq1 or not sa1 or not sq2 or not sa2:
        raise ValueError("Both security questions and answers must be filled out.")
    if sq1 == sq2:
        raise ValueError("Please select two different security questions.")
    
    referred_by_code = referred_by_code.strip() if referred_by_code else None
    if referred_by_code:
        if not verify_invite_code(referred_by_code):
            raise ValueError("Invalid or expired invite referral code.")
            
    pwd_hash, salt = hash_password(password)
    
    # Secure salt for questions
    salt_questions = secrets.token_hex(16)
    sa1_clean = sa1.strip().lower()
    sa2_clean = sa2.strip().lower()
    
    sa1_hash, _ = hash_password(sa1_clean, salt_questions)
    sa2_hash, _ = hash_password(sa2_clean, salt_questions)
    
    conn = sqlite3.connect(DB_FILE)
    cur = conn.cursor()
    try:
        # Get allotted credits from invite code if any
        allotted_credits = None
        if referred_by_code:
            cur.execute("SELECT allotted_credits FROM invite_codes WHERE code = ?", (referred_by_code,))
            row = cur.fetchone()
            if row:
                allotted_credits = row[0]
                
        # Insert user
        encrypted_email = crypto_utils.encrypt_data(email) if email else None
        cur.execute(
            """
            INSERT INTO users (
                username, password_hash, salt, email,
                security_question_1, security_answer_hash_1,
                security_question_2, security_answer_hash_2,
                salt_questions, referred_by_code, credits_remaining
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (username, pwd_hash, salt, encrypted_email, sq1, sa1_hash, sq2, sa2_hash, salt_questions, referred_by_code, allotted_credits)
        )
        # Update code count
        if referred_by_code:
            cur.execute(
                "UPDATE invite_codes SET used_count = used_count + 1 WHERE code = ?",
                (referred_by_code,)
            )
        conn.commit()
        return True
    except sqlite3.IntegrityError:
        raise ValueError(f"Username '{username}' already exists. Please choose a different one.")
    finally:
        conn.close()


# =========================================================================
# 3. Authentication & Password Reset
# =========================================================================

def authenticate_user(username: str, password: str) -> bool:
    """Authenticate credentials against database."""
    username = username.strip()
    if not username:
        return False
        
    conn = sqlite3.connect(DB_FILE)
    cur = conn.cursor()
    cur.execute("SELECT password_hash, salt FROM users WHERE username = ?", (username,))
    row = cur.fetchone()
    conn.close()
    
    if row:
        pwd_hash, salt = row[0], row[1]
        return verify_password(password, pwd_hash, salt)
    return False

def get_user_security_questions(username: str) -> list:
    """Retrieve security questions registered by the user."""
    username = username.strip()
    conn = sqlite3.connect(DB_FILE)
    cur = conn.cursor()
    cur.execute("SELECT security_question_1, security_question_2 FROM users WHERE username = ?", (username,))
    row = cur.fetchone()
    conn.close()
    return list(row) if row else None

def reset_password_via_questions(username: str, sa1: str, sa2: str, new_password: str) -> bool:
    """Validate answers and update user password in SQLite database."""
    username = username.strip()
    if len(new_password) < 4:
        raise ValueError("Password must be at least 4 characters long.")
        
    conn = sqlite3.connect(DB_FILE)
    cur = conn.cursor()
    
    cur.execute(
        "SELECT security_answer_hash_1, security_answer_hash_2, salt_questions FROM users WHERE username = ?",
        (username,)
    )
    row = cur.fetchone()
    
    if not row:
        conn.close()
        return False
        
    sa1_hash, sa2_hash, salt_questions = row[0], row[1], row[2]
    
    sa1_clean = sa1.strip().lower()
    sa2_clean = sa2.strip().lower()
    
    verify_sa1 = verify_password(sa1_clean, sa1_hash, salt_questions)
    verify_sa2 = verify_password(sa2_clean, sa2_hash, salt_questions)
    
    if verify_sa1 and verify_sa2:
        new_pwd_hash, new_salt = hash_password(new_password)
        cur.execute(
            "UPDATE users SET password_hash = ?, salt = ? WHERE username = ?",
            (new_pwd_hash, new_salt, username)
        )
        conn.commit()
        conn.close()
        return True
    else:
        conn.close()
        return False

# =========================================================================
# 4. Streamlit UI Gatekeeper & Referrals UI
# =========================================================================

def check_authentication():
    """Gatekeeper function. If not authenticated, displays login/registration/recovery forms and stops execution."""
    if "authenticated" not in st.session_state:
        st.session_state["authenticated"] = False
        st.session_state["username"] = None

    # Hide default Streamlit sidebar navigation globally (we use custom st.page_link widgets)
    st.markdown(
        """
        <style>
            [data-testid="stSidebarNav"] {
                display: none !important;
            }
        </style>
        """,
        unsafe_allow_html=True
    )

    if not st.session_state["authenticated"]:
        # Custom CSS when not authenticated
        st.markdown(
            """
            <style>
                .main {
                    background-color: #0f1116;
                    color: #e2e8f0;
                }
            </style>
            """,
            unsafe_allow_html=True
        )
        
        # Center login box beautifully
        col_space1, col_form, col_space2 = st.columns([1, 2, 1])
        with col_form:
            st.title("🔒 BioIntelligence Platform")
            st.subheader("Secure Access Gateway")
            st.write("Please log in, register a free account, or recover your password to continue.")
            
            auth_tab1, auth_tab2, auth_tab3 = st.tabs(["🔑 Sign In", "📝 Create Account", "❓ Forgot Password"])
            
            with auth_tab1:
                with st.form("login_form"):
                    username = st.text_input("Username")
                    password = st.text_input("Password", type="password")
                    submit = st.form_submit_button("Sign In", use_container_width=True)
                    if submit:
                        if authenticate_user(username, password):
                            st.session_state["authenticated"] = True
                            st.session_state["username"] = username
                            st.success("Successfully logged in!")
                            st.rerun()
                        else:
                            st.error("Invalid username or password.")
                            
            with auth_tab2:
                with st.form("register_form"):
                    st.write("**Account Details**")
                    new_user = st.text_input("Username")
                    new_email = st.text_input("Email (optional)")
                    new_pass = st.text_input("Password (min 4 chars)", type="password")
                    confirm_pass = st.text_input("Confirm Password", type="password")
                    
                    st.write("---")
                    st.write("**Security Questions (for Password Recovery)**")
                    sq1 = st.selectbox("Security Question 1", SECURITY_QUESTIONS, index=0)
                    sa1 = st.text_input("Answer 1")
                    sq2 = st.selectbox("Security Question 2", SECURITY_QUESTIONS, index=1)
                    sa2 = st.text_input("Answer 2")
                    
                    st.write("---")
                    st.write("**Referral Verification**")
                    invite_code = st.text_input("Invite / Referral Code", placeholder="Invite code (Default: BIOINTEL2026)")
                    
                    submit = st.form_submit_button("Create Account", use_container_width=True)
                    if submit:
                        if not invite_code.strip():
                            st.error("An invite or referral code is required to register.")
                        elif not verify_invite_code(invite_code):
                            st.error("Invalid, expired, or fully-used referral code.")
                        elif not new_user.strip() or not new_pass.strip():
                            st.error("Username and password cannot be empty.")
                        elif new_pass != confirm_pass:
                            st.error("Passwords do not match.")
                        elif not sa1.strip() or not sa2.strip():
                            st.error("Please answer both security questions.")
                        elif sq1 == sq2:
                            st.error("Please select two different security questions.")
                        else:
                            try:
                                register_user(
                                    username=new_user, 
                                    password=new_pass, 
                                    email=new_email if new_email.strip() else None,
                                    sq1=sq1, 
                                    sa1=sa1, 
                                    sq2=sq2, 
                                    sa2=sa2,
                                    referred_by_code=invite_code
                                )
                                st.success("Account created successfully! Please sign in using the Sign In tab.")
                            except ValueError as e:
                                st.error(str(e))
                                
            with auth_tab3:
                st.write("**Reset Password via Security Questions**")
                
                if "recovery_username" not in st.session_state:
                    st.session_state["recovery_username"] = ""
                if "recovery_questions" not in st.session_state:
                    st.session_state["recovery_questions"] = None
                
                rec_user = st.text_input("Enter your Username", value=st.session_state["recovery_username"])
                if st.button("Retrieve Security Questions", use_container_width=True):
                    if rec_user.strip():
                        questions = get_user_security_questions(rec_user)
                        if questions:
                            st.session_state["recovery_questions"] = questions
                            st.session_state["recovery_username"] = rec_user.strip()
                        else:
                            st.error("Username not found.")
                            st.session_state["recovery_questions"] = None
                    else:
                        st.error("Please enter a username.")
                
                if st.session_state["recovery_questions"]:
                    st.write("---")
                    st.info("Username verified. Please answer your security questions to set a new password:")
                    
                    with st.form("recovery_answers_form"):
                        q1, q2 = st.session_state["recovery_questions"][0], st.session_state["recovery_questions"][1]
                        st.write(f"**Q1:** {q1}")
                        ans1 = st.text_input("Answer 1", key="ans1_rec")
                        
                        st.write(f"**Q2:** {q2}")
                        ans2 = st.text_input("Answer 2", key="ans2_rec")
                        
                        st.write("---")
                        new_pwd = st.text_input("New Password", type="password")
                        confirm_new_pwd = st.text_input("Confirm New Password", type="password")
                        
                        submit_reset = st.form_submit_button("Reset Password", use_container_width=True)
                        if submit_reset:
                            if not ans1.strip() or not ans2.strip():
                                st.error("Please answer both questions.")
                            elif new_pwd != confirm_new_pwd:
                                st.error("Passwords do not match.")
                            elif len(new_pwd) < 4:
                                st.error("Password must be at least 4 characters.")
                            else:
                                success = reset_password_via_questions(
                                    username=st.session_state["recovery_username"],
                                    sa1=ans1,
                                    sa2=ans2,
                                    new_password=new_pwd
                                )
                                if success:
                                    st.success("Password reset successfully! You can now log in using the Sign In tab.")
                                    st.session_state["recovery_username"] = ""
                                    st.session_state["recovery_questions"] = None
                                else:
                                    st.error("Incorrect security answers. Password reset failed.")
        st.stop()
    else:
        # Show username and logout button in sidebar
        st.sidebar.markdown("---")
        st.sidebar.markdown(f"👤 Logged in as: **{st.session_state['username']}**")
        if st.sidebar.button("Log Out", use_container_width=True):
            st.session_state["authenticated"] = False
            st.session_state["username"] = None
            st.rerun()

def render_referral_dashboard():
    """Renders the referral auditing and generation forms in Streamlit UI."""
    st.header("👤 Team Referrals & Access Logs")
    st.write("Generate unique invite codes for new employees and track who shared their codes and who signed up.")
    
    col_gen, col_codes = st.columns([1, 2])
    username = st.session_state.get("username")
    
    with col_gen:
        st.subheader("Generate Invite Code")
        max_uses = st.number_input("Max Allowed Uses", min_value=1, max_value=1000, value=1)
        is_limited = st.checkbox("Credit Limited (Demo)", value=False)
        allotted_credits = None
        if is_limited:
            allotted_credits = st.number_input("Allotted Credits", min_value=1, max_value=100, value=3)
            
        if st.button("Generate Invite Code", use_container_width=True):
            code = generate_referral_code(username, max_uses, allotted_credits)
            st.success(f"Generated Code: `{code}`")
            st.rerun()
            
    with col_codes:
        st.subheader("Your Generated Invite Codes")
        df_my_codes = get_user_referral_codes(username)
        if not df_my_codes.empty:
            # Map None/NaN to 'Unlimited' for display
            df_my_codes["allotted_credits"] = df_my_codes["allotted_credits"].apply(
                lambda x: "Unlimited" if pd.isna(x) or x is None else int(x)
            )
            df_my_codes.columns = ["Invite Code", "Max Uses", "Used Count", "Status", "Allotted Credits", "Created At"]
            st.dataframe(df_my_codes, use_container_width=True)
        else:
            st.info("You haven't generated any invite codes yet.")
            
    st.markdown("---")
    st.subheader("Audit Log: Registered Employees & Referrers")
    st.write("Track exactly who registered, when they signed up, and which employee's invite code was used.")
    
    df_audit = get_referral_audit_log()
    if not df_audit.empty:
        df_audit["initial_credits"] = df_audit["initial_credits"].apply(
            lambda x: "Unlimited" if pd.isna(x) or x is None else int(x)
        )
        df_audit["remaining_credits"] = df_audit["remaining_credits"].apply(
            lambda x: "Unlimited" if pd.isna(x) or x is None else int(x)
        )
        df_audit.columns = [
            "Registered User", "Registered Date", "Invite Code Used", 
            "Inviting Employee / Owner", "Initial Credits", "Remaining Credits"
        ]
        st.dataframe(df_audit, use_container_width=True)
    else:
        st.info("No referral registration logs found.")
